// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpQ_8fk9JQkn55bGueOaTTSSJMm7l6GR0',
    appId: '1:928573346270:android:2880b58a4ea7c93e014d4f',
    messagingSenderId: '928573346270',
    projectId: 'flix-id-course-12dc4',
    storageBucket: 'flix-id-course-12dc4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxrm7uISZar0GNplVh9XS6ZFZDPsMVT5o',
    appId: '1:928573346270:ios:e82866d95a5a4581014d4f',
    messagingSenderId: '928573346270',
    projectId: 'flix-id-course-12dc4',
    storageBucket: 'flix-id-course-12dc4.firebasestorage.app',
    iosBundleId: 'com.example.flixId',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6BmlL1kcU8keGtoRUteMZ3IbPqtREZWc',
    appId: '1:928573346270:web:a2045e66d37cefc9014d4f',
    messagingSenderId: '928573346270',
    projectId: 'flix-id-course-12dc4',
    authDomain: 'flix-id-course-12dc4.firebaseapp.com',
    storageBucket: 'flix-id-course-12dc4.firebasestorage.app',
    measurementId: 'G-26PX0DSX36',
  );

}